INSERT INTO bk_account VALUES ("1220", "0.0", "1", "Maskiner och inventarier");
INSERT INTO bk_account VALUES ("1500", "0.0", "1", "Kundfordringar");
INSERT INTO bk_account VALUES ("1930", "0.0", "1", "Checkräkningskonto");
INSERT INTO bk_account VALUES ("2010", "0.0", "0", "Eget kapital");
INSERT INTO bk_account VALUES ("2440", "0.0", "0", "Leverantörsskulder");
INSERT INTO bk_account VALUES ("2610", "0.0", "0", "Utgående moms  oreducerad");
INSERT INTO bk_account VALUES ("2614", "0.0", "0", "Beräknad utgående moms på tjänsteförvärv från utlandet  oreducerad");
INSERT INTO bk_account VALUES ("2640", "0.0", "0", "Ingående moms");
INSERT INTO bk_account VALUES ("2645", "0.0", "0", "Beräknad ingående moms på förvärv från utlandet");
INSERT INTO bk_account VALUES ("3000", "0.0", "0", "Försäljning och utfört arbete samt övriga momspliktiga intäkter");
INSERT INTO bk_account VALUES ("3100", "0.0", "0", "Momsfria intäkter");
INSERT INTO bk_account VALUES ("4000", "0.0", "1", "Varor");
INSERT INTO bk_account VALUES ("4600", "0.0", "1", "Legoarbeten och underentreprenader");
INSERT INTO bk_account VALUES ("5400", "0.0", "1", "Förbrukningsinventarier och förbrukningsmaterial");
INSERT INTO bk_account VALUES ("5500", "0.0", "1", "Reparation och underhåll");
INSERT INTO bk_account VALUES ("6100", "0.0", "1", "Kontorsmateriel och trycksaker");
INSERT INTO bk_account VALUES ("7830", "0.0", "1", "Avskrivningar på maskiner och inventarier");
INSERT INTO bk_account VALUES ("7960", "0.0", "1", "Valutakursförluster på fordringar och skulder av rörelsekaraktär");
