INSERT INTO bk_account VALUES (NULL, "1220", "0.0", "Maskiner och inventarier");
INSERT INTO bk_account VALUES (NULL, "1229", "0.0", "Årets avskrivningar på maskiner och inventarier");
INSERT INTO bk_account VALUES (NULL, "1500", "0.0", "Kundfordringar");
INSERT INTO bk_account VALUES (NULL, "1930", "0", "0 Checkräkningskonto");
INSERT INTO bk_account VALUES (NULL, "2013", "0.0", "Egna uttag");
INSERT INTO bk_account VALUES (NULL, "2017", "0.0", "Egna insättningar");
INSERT INTO bk_account VALUES (NULL, "2440", "0.0", "Leverantörsskulder");
INSERT INTO bk_account VALUES (NULL, "2610", "0.0", "Utgående moms  oreducerad");
INSERT INTO bk_account VALUES (NULL, "2614", "0.0", "Beräknad utgående moms på tjänsteförvärv från utlandet  oreducerad");
INSERT INTO bk_account VALUES (NULL, "2640", "0.0", "Ingående moms");
INSERT INTO bk_account VALUES (NULL, "2645", "0.0", "Beräknad ingående moms på förvärv från utlandet");
INSERT INTO bk_account VALUES (NULL, "3000", "0.0", "Försäljning och utfört arbete samt övriga momspliktiga intäkter");
INSERT INTO bk_account VALUES (NULL, "3100", "0.0", "Momsfria intäkter");
INSERT INTO bk_account VALUES (NULL, "4000", "0.0", "Varor");
INSERT INTO bk_account VALUES (NULL, "4600", "0.0", "Legoarbeten och underentreprenader");
INSERT INTO bk_account VALUES (NULL, "5400", "0.0", "Förbrukningsinventarier och förbrukningsmaterial");
INSERT INTO bk_account VALUES (NULL, "5500", "0.0", "Reparation och underhåll");
INSERT INTO bk_account VALUES (NULL, "6100", "0.0", "Kontorsmateriel och trycksaker");
INSERT INTO bk_account VALUES (NULL, "7960", "0.0", "Valutakursförluster på fordringar och skulder av rörelsekaraktär");
